### ISSUE TITLE
2.2 change method's name and format signature(remove spaces)

### ISSUE THREAD

**Issue by alexCherrySfds2019** [a3dot14makh/sf-senla-courses#1]
https://github.com/a3dot14makh/sf-senla-courses/blob/bfa325964729921f43ab886c015eb71e088b2a37/lecture_2.2/TouristManager.cls#L2

List < Tourist__c > showTouristsByName -> List<Tourist__c>getByName

Tourist - избыточное слово
get лучше чем  show

**Comment by a3dot14makh** [comment]
Исправил
