### ISSUE TITLE
3.4 show informative msg for User that component is unavailable

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#103]
https://github.com/a3dot14makh/sf-senla-courses/blob/113c340332974f118cd1f00759a136168b1ea1d0/lecture_3.4/auraComponent/TableSuitableTouristsForTrip/TableSuitableTouristsForTrip.cmp#L18

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/4f4b49fd3f711f4973ac699bfb87abab474f2f3b/lecture_3.4/aura/TableSuitableTouristsForTrip/TableSuitableTouristsForTrip.cmp#L67

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/main/lecture_3.4/screenshots/task1/0_There%20are%20no%20suitable%20tourists.png

**Comment by alexCherrySfds2019** [comment]
@NikitaErmakSenla  could be closed
