### ISSUE TITLE
3.4. param event is never used

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#107]
https://github.com/a3dot14makh/sf-senla-courses/blob/113c340332974f118cd1f00759a136168b1ea1d0/lecture_3.4/auraComponent/TableSuitableTouristsForTrip/TableSuitableTouristsForTripHelper.js#L2

**Comment by a3dot14makh** [comment]
Done

**Comment by alexCherrySfds2019** [comment]
@NikitaErmakSenla  could be closed
