### ISSUE TITLE
3.4. use js method Array.map

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#109]
https://github.com/a3dot14makh/sf-senla-courses/blob/113c340332974f118cd1f00759a136168b1ea1d0/lecture_3.4/auraComponent/TableSuitableTouristsForTrip/TableSuitableTouristsForTripHelper.js#L54

**Comment by NikitaErmakSenla** [comment]
let result = objArray.map(a => a.foo);

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/4f4b49fd3f711f4973ac699bfb87abab474f2f3b/lecture_3.4/aura/TableSuitableTouristsForTrip/TableSuitableTouristsForTripHelper.js#L52

**Comment by alexCherrySfds2019** [comment]
@NikitaErmakSenla could be closed
