### ISSUE TITLE
2.4 exception doesn't leave the method

### ISSUE THREAD

**Issue by alexCherrySfds2019** [a3dot14makh/sf-senla-courses#11]
https://github.com/a3dot14makh/sf-senla-courses/blob/3a8db34086827c9a429d6d7b7a58257891c38207/lecture_2.4/ExceptionHw.cls#L13

**Comment by a3dot14makh** [comment]
Не совсем понял задание изначально :)
Всё исправил.

https://github.com/a3dot14makh/sf-senla-courses/blob/646e8b871bc7ddd9bac649884b51d7345acac376/lecture_2.4/ExceptionsPlayground.cls#L10
