### ISSUE TITLE
2.3 improve the logic

### ISSUE THREAD

**Issue by alexCherrySfds2019** [a3dot14makh/sf-senla-courses#12]
https://github.com/a3dot14makh/sf-senla-courses/blob/11c7c4f4f8d50595001dea279f2f48fcf7d526a2/lecture_2.3/TouristTriggerHandler.cls#L2

is it used anywhere?

**Comment by a3dot14makh** [comment]
i'm sorry. Не запушил просто)

https://github.com/a3dot14makh/sf-senla-courses/blob/7dc4a7781e960686d611df8864261e84e1da4883/lecture_2.3/TouristTrigger.trigger#L2

https://github.com/a3dot14makh/sf-senla-courses/blob/7dc4a7781e960686d611df8864261e84e1da4883/lecture_2.3/FlightTrigger.trigger#L2

Использовал переменную wasExecuted для предотвращения рекурсии в триггерах.
