### ISSUE TITLE
2.3 move the logic to TouristService.markDuplicates

### ISSUE THREAD

**Issue by alexCherrySfds2019** [a3dot14makh/sf-senla-courses#13]
https://github.com/a3dot14makh/sf-senla-courses/blob/11c7c4f4f8d50595001dea279f2f48fcf7d526a2/lecture_2.3/TouristTriggerHandler.cls#L4

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/93672a1ba2b567d3ad4f10f3f1582028b880f011/lecture_2.3/TouristTriggerHandler.cls#L9
