### ISSUE TITLE
2.5 Why callout=true?

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#18]
https://github.com/a3dot14makh/sf-senla-courses/blob/6442db1693aaef6010a6a62950550be23bd990e7/lecture_2.5/TouristService.cls#L30

**Comment by a3dot14makh** [comment]
Бездумно скопировал( 
Но вообще этот параметр нужен, если future-метод будет обращаться к внешним ресурсам(например: http-запрос). 
https://github.com/a3dot14makh/sf-senla-courses/blob/09f305dd21a9672495489ac8bbc516a7a352df89/lecture_2.5/TouristService.cls#L28

**Comment by NikitaErmakSenla** [comment]
Не надо бездумно копировать :)
