### ISSUE TITLE
2.2 use array instead of 3 params

### ISSUE THREAD

**Issue by alexCherrySfds2019** [a3dot14makh/sf-senla-courses#2]
https://github.com/a3dot14makh/sf-senla-courses/blob/bfa325964729921f43ab886c015eb71e088b2a37/lecture_2.2/TouristManager.cls#L14

**Comment by a3dot14makh** [comment]
Исправил
https://github.com/a3dot14makh/sf-senla-courses/blob/cb9eca802f53cf2d15331f595e102d95903f9c86/lecture_2.2/TouristManager.cls#L15
