### ISSUE TITLE
2.5 Format: empty line before for()

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#20]
https://github.com/a3dot14makh/sf-senla-courses/blob/6442db1693aaef6010a6a62950550be23bd990e7/lecture_2.5/TouristService.cls#L35

**Comment by a3dot14makh** [comment]
Fixed

https://github.com/a3dot14makh/sf-senla-courses/blob/09f305dd21a9672495489ac8bbc516a7a352df89/lecture_2.5/TouristService.cls#L34

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/eacdbe00888b2a4a7d28553d76146dfda1234c7b/lecture_2.5/TouristService.cls#L11
