### ISSUE TITLE
2.5 Move this logic to somewhere else

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#24]
https://github.com/a3dot14makh/sf-senla-courses/blob/6442db1693aaef6010a6a62950550be23bd990e7/lecture_2.5/DeleteFlightsBatch.cls#L35

**Comment by NikitaErmakSenla** [comment]
E.g. 
create private method inside Batch that will do the job

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/09f305dd21a9672495489ac8bbc516a7a352df89/lecture_2.5/DeleteFlightsBatch.cls#L39

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/eacdbe00888b2a4a7d28553d76146dfda1234c7b/lecture_2.5/DeleteFlightsBatch.cls#L51
