### ISSUE TITLE
2.5 L2-6 - in one line

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#25]
https://github.com/a3dot14makh/sf-senla-courses/blob/6442db1693aaef6010a6a62950550be23bd990e7/lecture_2.5/EmailService.cls#L2

**Comment by NikitaErmakSenla** [comment]
Total chars = 113 (<120)

**Comment by a3dot14makh** [comment]
After the changes in the logic, there are more symbols. 

https://github.com/a3dot14makh/sf-senla-courses/blob/eacdbe00888b2a4a7d28553d76146dfda1234c7b/lecture_2.5/EmailService.cls#L3
