### ISSUE TITLE
2.5 Format : empty line before method

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#27]
https://github.com/a3dot14makh/sf-senla-courses/blob/6442db1693aaef6010a6a62950550be23bd990e7/lecture_2.5/TouristSettingManager.cls#L2

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/eacdbe00888b2a4a7d28553d76146dfda1234c7b/lecture_2.5/GeneralMetadataManager.cls#L3
