### ISSUE TITLE
2.5 Format : empty line before for()

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#28]
https://github.com/a3dot14makh/sf-senla-courses/blob/6442db1693aaef6010a6a62950550be23bd990e7/lecture_2.5/TouristSettingManager.cls#L8

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/09f305dd21a9672495489ac8bbc516a7a352df89/lecture_2.5/GeneralMetadataManager.cls#L9
