### ISSUE TITLE
2.5 Use Set<String> to avoid duplicates

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#29]
https://github.com/a3dot14makh/sf-senla-courses/blob/6442db1693aaef6010a6a62950550be23bd990e7/lecture_2.5/EmailService.cls#L3

**Comment by a3dot14makh** [comment]
I implemented it this way: 
https://github.com/a3dot14makh/sf-senla-courses/blob/eacdbe00888b2a4a7d28553d76146dfda1234c7b/lecture_2.5/GeneralMetadataManager.cls#L13
