### ISSUE TITLE
2.2 add input validation

### ISSUE THREAD

**Issue by alexCherrySfds2019** [a3dot14makh/sf-senla-courses#3]
https://github.com/a3dot14makh/sf-senla-courses/blob/bfa325964729921f43ab886c015eb71e088b2a37/lecture_2.2/TouristManager.cls#L14

и просмотри остальные методы

**Comment by alexCherrySfds2019** [comment]
1) добавь проверку на yearOfFlightStart == null
https://github.com/a3dot14makh/sf-senla-courses/blob/62275f42a5e33f23a5795bfaf525c2af0ef2b578/lecture_2.2/TouristManager.cls#L27
2)

**Comment by a3dot14makh** [comment]
"добавь проверку на yearOfFlightStart == null" а можешь привести пример такой ситуации. Потому что я пробовал воспроизвести эту ситуацию в Ананимусе, но у меня не получается. 
Если я создал переменную Integer a = null и использовал её в качестве параметра метода, то мне выдаёт System.NullPointerException , но ведь по логике должен вернуть пустой лист. Если ничего не ввожу в качестве параметра метода, то тоже выдаётся ошибка: Method does not exist or incorrect signature

**Comment by a3dot14makh** [comment]
> 1. добавь проверку на yearOfFlightStart == null
>    https://github.com/a3dot14makh/sf-senla-courses/blob/62275f42a5e33f23a5795bfaf525c2af0ef2b578/lecture_2.2/TouristManager.cls#L27

а можешь привести пример такой ситуации. Потому что я пробовал воспроизвести эту ситуацию в Ананимусе, но у меня не получается.
Если я создал переменную Integer a = null и использовал её в качестве параметра метода, то мне выдаёт System.NullPointerException , но ведь по логике должен вернуть пустой лист. Если ничего не ввожу в качестве параметра метода, то тоже выдаётся ошибка: Method does not exist or incorrect signature

**Comment by a3dot14makh** [comment]
Доработал валидацию.

**Comment by a3dot14makh** [comment]
А как быть с валидацией в методах которые ничего не возвращают. Типо мсю логику заключать в один большой if?
Например в том же методе по поиску дубликатов.
