### ISSUE TITLE
2.5.2 This code will never be executed (again)

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#30]
https://github.com/a3dot14makh/sf-senla-courses/blob/26fce7959f6dcf698d009658ae197fb3ee8f278b/lecture_2.5/TouristTriggerHandler.cls#L4

**Comment by a3dot14makh** [comment]
Fixed
https://github.com/a3dot14makh/sf-senla-courses/blob/9e9ace72e7984b0430934f952bb5778e265d8ba8/lecture_2.5/TouristTriggerHandler.cls#L1
