### ISSUE TITLE
2.5.2 private for internal class use vars

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#32]
https://github.com/a3dot14makh/sf-senla-courses/blob/26fce7959f6dcf698d009658ae197fb3ee8f278b/lecture_2.5/DeleteFlightsBatch.cls#L11

**Comment by a3dot14makh** [comment]
Okay, thanks)
https://github.com/a3dot14makh/sf-senla-courses/blob/9e9ace72e7984b0430934f952bb5778e265d8ba8/lecture_2.5/DeleteFlightsBatch.cls#L11
