### ISSUE TITLE
2.5.2 simplify

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#33]
https://github.com/a3dot14makh/sf-senla-courses/blob/26fce7959f6dcf698d009658ae197fb3ee8f278b/lecture_2.5/TouristTriggerHandler.cls#L19

**Comment by NikitaErmakSenla** [comment]
`oldMap.get(tourist.Id).Active__c &&  !newMap.get(tourist.Id).Active__c`

**Comment by a3dot14makh** [comment]
Fixed
https://github.com/a3dot14makh/sf-senla-courses/blob/9e9ace72e7984b0430934f952bb5778e265d8ba8/lecture_2.5/TouristTriggerHandler.cls#L15
