### ISSUE TITLE
2.5.2 bad naming

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#35]
https://github.com/a3dot14makh/sf-senla-courses/blob/26fce7959f6dcf698d009658ae197fb3ee8f278b/lecture_2.5/ScheduledBatch.cls#L1

**Comment by a3dot14makh** [comment]
Fixed. 
Я просто думал, что класс Scheduled будет использоваться для всех Batch. А оказалось: на каждый Batch отдельный Scheduled.
https://github.com/a3dot14makh/sf-senla-courses/blob/f53d0ed47bbc1d51eb3aba4fec11b0505cdbe59d/lecture_2.5/DeleteFlightsScheduled.cls#L1
