### ISSUE TITLE
2.5.2 Naming - tourists

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#36]
https://github.com/a3dot14makh/sf-senla-courses/blob/26fce7959f6dcf698d009658ae197fb3ee8f278b/lecture_2.5/DeleteFlightsBatch.cls#L23

**Comment by a3dot14makh** [comment]
The name "tourists" is already in the class.
https://github.com/a3dot14makh/sf-senla-courses/blob/f53d0ed47bbc1d51eb3aba4fec11b0505cdbe59d/lecture_2.5/DeleteFlightsBatch.cls#L13

**Comment by NikitaErmakSenla** [comment]
Still relevant. Your code won't work

**Comment by a3dot14makh** [comment]
Исправил:)
Я просто часть последних коммитов не из исходников делал, поэтому и неразбериха вышла.
