### ISSUE TITLE
2.5.2 Why do you need to sort?

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#37]
https://github.com/a3dot14makh/sf-senla-courses/blob/26fce7959f6dcf698d009658ae197fb3ee8f278b/lecture_2.5/DeleteFlightsBatch.cls#L34

**Comment by NikitaErmakSenla** [comment]
sort all the tourists then

**Comment by a3dot14makh** [comment]
В личку отвечвл на этот вопрос. Я перенёс это действие в метод, который создаёт htmBody и вызывается из finish
 https://github.com/a3dot14makh/sf-senla-courses/blob/f53d0ed47bbc1d51eb3aba4fec11b0505cdbe59d/lecture_2.5/DeleteFlightsBatch.cls#L52
