### ISSUE TITLE
2.5.2 class.getName()

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#38]
https://github.com/a3dot14makh/sf-senla-courses/blob/26fce7959f6dcf698d009658ae197fb3ee8f278b/lecture_2.5/BatchApexErrorEventTriggerHandler.cls#L15

**Comment by NikitaErmakSenla** [comment]
DeleteFlightsBatch.class.getName()

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/f53d0ed47bbc1d51eb3aba4fec11b0505cdbe59d/lecture_2.5/BatchApexErrorEventTriggerHandler.cls#L15
