### ISSUE TITLE
2.2 for each field in SOQL - new line

### ISSUE THREAD

**Issue by alexCherrySfds2019** [a3dot14makh/sf-senla-courses#4]
https://github.com/a3dot14makh/sf-senla-courses/blob/bfa325964729921f43ab886c015eb71e088b2a37/lecture_2.2/TouristManager.cls#L8

вместо SELECT Name, Age__c

лучше
SELECT Name,
Age__c

если будет SELECT Name, Age__c, (SELECT Trip__r.Name, Trip__r.Start_Date__c FROM flying__r)

можно
SELECT Name,
Age__c,
(SELECT Trip__r.Name, Trip__r.Start_Date__c FROM flying__r)

или если внутренни запрос слишком длинный (не влезает в экран) его также можно разбить
SELECT Name,
Age__c,
(SELECT Trip__r.Name,
Trip__r.Start_Date__c
FROM flying__r)

**Comment by a3dot14makh** [comment]
А можно в Prettier настроить, чтобы он автоматом переводил поле на новую строку?

**Comment by alexCherrySfds2019** [comment]
честно говоря не знаю) Почему-то кажется что нет, возможно какие-то расширения есть

**Comment by a3dot14makh** [comment]
Готово)

**Comment by alexCherrySfds2019** [comment]
тут еще поправить надо

https://github.com/a3dot14makh/sf-senla-courses/blob/11c7c4f4f8d50595001dea279f2f48fcf7d526a2/lecture_2.2/TouristManager.cls#L6

**Comment by a3dot14makh** [comment]
Поправил

https://github.com/a3dot14makh/sf-senla-courses/blob/f94c94941a115c496370a9c96e6c98812e603c40/lecture_2.2/TouristManager.cls#L6
