### ISSUE TITLE
2.6.1 inappropriate use for try / catch

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#42]
https://github.com/a3dot14makh/sf-senla-courses/blob/0d85fa84c5e1693998aed1f7e59fe093e6235501/lecture_2.6/TouristRestService.cls#L23

**Comment by NikitaErmakSenla** [comment]
String.isNumeric()

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/c68b266053a793a3d9d491b150b9c457762d6320/lecture_2.6/TouristRestService.cls#L72
