### ISSUE TITLE
2.6.1 by requirements this API should support 1 tourist (not list)

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#48]
https://github.com/a3dot14makh/sf-senla-courses/blob/0d85fa84c5e1693998aed1f7e59fe093e6235501/lecture_2.6/TouristRestService.cls#L38

**Comment by a3dot14makh** [comment]
Вроде как договорились, что можно так оставить. Но я понял, что код писать нужно строго по ТЗ.
