### ISSUE TITLE
2.2 Map <Tourist__c, List <Trip__c>> showTouristsWithFlights - name doesn't match to the returned value

### ISSUE THREAD

**Issue by alexCherrySfds2019** [a3dot14makh/sf-senla-courses#5]
https://github.com/a3dot14makh/sf-senla-courses/blob/bfa325964729921f43ab886c015eb71e088b2a37/lecture_2.2/TouristManager.cls#L40

1) Метод называется showTouristsWithFlights, а возвращаешь туристов с трипами
2) обычно для мап применяются названия типа showTouristsToFlights  либо showFlightsByTourist
3) и самое главное - этот метод будет обслуживать очень спицифический круг задач, то есть если где-то эта мапа будет не нужна, нужнен будет простой личст, то надо будет либо переделывать этот метод (и все места где он используется) (затраты времени), либо создавать новый (дублирование кода), либо усложнять то место, где нужен лист(затраты времени). Поэтому этот вариант допустим, но с архитектурной точки зрения это мина.

**Comment by a3dot14makh** [comment]
1. Название поменял.
3. Я понял что ты имеешь ввиду. Я видимо слишком серьёзно подошёл к заданию; "выбрать туристов (имя, возраст) со списком рейсов (дата старта, название)"
Решение проще - это вернуть сразу List с SOQL запросом.
Если можно, то я оставлю вариант с Мапой для примера.

**Comment by alexCherrySfds2019** [comment]
хорошо, оставляй для примера, но давай тогда улучшим: вынеси этот метод в сервис, а запрос в базу из метода вынеси в менеджер (для этого запроса сосдай свой метод). Тогда все будет ок.

Потом меня просто побъют если увидят такое в менеджере)

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/98415924ee3e730c412928860f500030a3514b76/lecture_2.2/TouristService.cls#L31

https://github.com/a3dot14makh/sf-senla-courses/blob/98415924ee3e730c412928860f500030a3514b76/lecture_2.2/TouristManager.cls#L54

Готово)
