### ISSUE TITLE
2.6.1 method is too long 

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#50]
https://github.com/a3dot14makh/sf-senla-courses/blob/0d85fa84c5e1693998aed1f7e59fe093e6235501/lecture_2.6/WeatherForecastUpdater.cls#L4

**Comment by NikitaErmakSenla** [comment]
simplify or move logic to somewhere

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/8560c78974cce7d266dd5e9af945d80cc944df5a/lecture_2.6/WeatherForecastUpdater.cls#L1
