### ISSUE TITLE
2.6.1 bad naming 'meta'

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#54]
https://github.com/a3dot14makh/sf-senla-courses/blob/0d85fa84c5e1693998aed1f7e59fe093e6235501/lecture_2.6/WeatherForecastService.cls#L10

**Comment by NikitaErmakSenla** [comment]
E.g. 'forecastsUntyped'

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/374e829604acbdd3511c2d700bfb8e1fd5c2ebda/lecture_2.6/WeatherbitAPIService.cls#L24
