### ISSUE TITLE
2.6.1 System.error()

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#58]
https://github.com/a3dot14makh/sf-senla-courses/blob/0d85fa84c5e1693998aed1f7e59fe093e6235501/lecture_2.6/WeatherForecastUpdater.cls#L20

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/70e00d8f22a4a7f8596505126823cf27c024c594/lecture_2.6/WeatherForecastService.cls#L28
