### ISSUE TITLE
2.2 KISS

### ISSUE THREAD

**Issue by alexCherrySfds2019** [a3dot14makh/sf-senla-courses#6]
https://github.com/a3dot14makh/sf-senla-courses/blob/62275f42a5e33f23a5795bfaf525c2af0ef2b578/lecture_2.2/NumberUtility.cls#L48

вот эту часть:
Boolean checkingPalindromicity = false;
if (num == numReverse) {
checkingPalindromicity = true;
}

return checkingPalindromicity;

можно заменить на 
return num == numReverse;

**Comment by a3dot14makh** [comment]
Переписал.

**Comment by alexCherrySfds2019** [comment]
лучше пока не видел)
