### ISSUE TITLE
2.6.2 not error, rebuild logic

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#60]
https://github.com/a3dot14makh/sf-senla-courses/blob/70e00d8f22a4a7f8596505126823cf27c024c594/lecture_2.6/TouristRestService.cls#L69

**Comment by NikitaErmakSenla** [comment]
There is no validation error. Move to getTourists() method

**Comment by NikitaErmakSenla** [comment]
still relevant

**Comment by a3dot14makh** [comment]
Не совсем понимаю, что мне нужно сделать? Ведь по условию "Допускается отсутствие параметра age", а значит и ошибки в том, что параметр age - пустой, нету.

**Comment by NikitaErmakSenla** [comment]
Logic is correct. But method validateRequestParams() is not supposed to process success cases. 
RestRequestValidationException should be used only if there was validation **error**

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/4a620fad8bda77c761a2f0498628d0df8e15cc46/lecture_2.6/TouristRestService.cls#L20
