### ISSUE TITLE
2.6.2 handle WeatherForecastException

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#66]
https://github.com/a3dot14makh/sf-senla-courses/blob/70e00d8f22a4a7f8596505126823cf27c024c594/lecture_2.6/WeatherForecastService.cls#L27

**Comment by NikitaErmakSenla** [comment]
still relevant

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/f69123f0d61060627c0ae3f67116d046eee5ce78/lecture_2.6/WeatherForecastService.cls#L15
