### ISSUE TITLE
2.6.2 no need for this check

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#67]
https://github.com/a3dot14makh/sf-senla-courses/blob/70e00d8f22a4a7f8596505126823cf27c024c594/lecture_2.6/WeatherForecastService.cls#L31

**Comment by NikitaErmakSenla** [comment]
still relevant

**Comment by a3dot14makh** [comment]
Я убрал эту проверку. Насколько я понял, она здесь не нужна, т.к. при пустой Мапе ошибки для следующей логики нету, а null-евой она никак не будет.
