### ISSUE TITLE
2.2 move SOQLs to manager

### ISSUE THREAD

**Issue by alexCherrySfds2019** [a3dot14makh/sf-senla-courses#7]
https://github.com/a3dot14makh/sf-senla-courses/blob/62275f42a5e33f23a5795bfaf525c2af0ef2b578/lecture_2.2/TouristService.cls#L10

**Comment by a3dot14makh** [comment]
Готово
https://github.com/a3dot14makh/sf-senla-courses/blob/3a8db34086827c9a429d6d7b7a58257891c38207/lecture_2.2/TouristManager.cls#L80
