### ISSUE TITLE
2.7.1 Naming combo

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#71]
https://github.com/a3dot14makh/sf-senla-courses/blob/0148214892147fb181e66d417297ca0f73754602/lecture_2.7/TestDataFactory.cls#L8

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/780c6ff0e8862162ac89b903f4302d62abccd8db/lecture_2.7/TestDataFactory.cls#L8

**Comment by NikitaErmakSenla** [comment]
Still relevant
**M**ath.**r**andom()

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/f8f3397e695b044f6e982e7c7eb44a4c9036ba60/lecture_2.7/TestDataFactory.cls#L8
