### ISSUE TITLE
2.7.1 Add additional asserts

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#72]
https://github.com/a3dot14makh/sf-senla-courses/blob/0148214892147fb181e66d417297ca0f73754602/lecture_2.7/TouristManagerTest.cls#L26

**Comment by NikitaErmakSenla** [comment]
First of all:
1) Check if not null;
2) Check size;
3) _Yours_;

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/780c6ff0e8862162ac89b903f4302d62abccd8db/lecture_2.7/TouristManagerTest.cls#L32

**Comment by NikitaErmakSenla** [comment]
Still relevant. 
Additional asserts - inside test-method

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/f8f3397e695b044f6e982e7c7eb44a4c9036ba60/lecture_2.7/TouristManagerTest.cls#L39
