### ISSUE TITLE
2.7.1 Use assertEquals for Booleans

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#73]
https://github.com/a3dot14makh/sf-senla-courses/blob/0148214892147fb181e66d417297ca0f73754602/lecture_2.7/TouristManagerTest.cls#L41

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/780c6ff0e8862162ac89b903f4302d62abccd8db/lecture_2.7/TouristManagerTest.cls#L21
