### ISSUE TITLE
2.7.2 FYI - usually insert is in TestDataFactory

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#79]
https://github.com/a3dot14makh/sf-senla-courses/blob/8c68bbbd6ffaa6b0e289907660c6105100c4190c/lecture_2.7/TestDataFactory.cls#L28

**Comment by NikitaErmakSenla** [comment]
But if you want to test trigger - ok

**Comment by a3dot14makh** [comment]
Ok, deleted.
