### ISSUE TITLE
2.2 could be improved - DONE, not closed by demand

### ISSUE THREAD

**Issue by alexCherrySfds2019** [a3dot14makh/sf-senla-courses#8]
https://github.com/a3dot14makh/sf-senla-courses/blob/62275f42a5e33f23a5795bfaf525c2af0ef2b578/lecture_2.2/TouristService.cls#L17

я не настаиваю, но можешь подумать как усовершенствовать это место (цикл в цикле). А вдруг придет очень много записей, и в базе много.
подсказка - использование Map

**Comment by a3dot14makh** [comment]
Вчера разобрали технологию;) Как будет время, попробую написать в таком ключе. Можешь не закрывать пока эту ошибку., чтоб как напоминание весело здесь.

**Comment by a3dot14makh** [comment]
Я переписал-таки логику(избавился от цикла в цикле), только обошёлся без Map. 
Если всё ОК, то можно закрывать эту issue :)
https://github.com/a3dot14makh/sf-senla-courses/blob/6f4e3c9861430ef4a2e012d100e8fe7535aae87a/lecture_2.2/TouristService.cls#L3

**Comment by NikitaErmakSenla** [comment]
Can be closed
