### ISSUE TITLE
2.7.2 Don't use assert()

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#83]
https://github.com/a3dot14makh/sf-senla-courses/blob/8c68bbbd6ffaa6b0e289907660c6105100c4190c/lecture_2.7/DeleteFlightsBatchTest.cls#L78

**Comment by NikitaErmakSenla** [comment]
`System.assertNotEquals(null, flightFromDB);`

**Comment by a3dot14makh** [comment]
I've learned.
