### ISSUE TITLE
2.7.2 more asserts: check for null, check if empty

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#85]
https://github.com/a3dot14makh/sf-senla-courses/blob/8c68bbbd6ffaa6b0e289907660c6105100c4190c/lecture_2.7/TouristRestServiceTest.cls#L29

**Comment by a3dot14makh** [comment]
Fixed in the whole file.
https://github.com/a3dot14makh/sf-senla-courses/blob/f8f3397e695b044f6e982e7c7eb44a4c9036ba60/lecture_2.7/TouristRestServiceTest.cls#L61
