### ISSUE TITLE
2.7.2 use @TestVisible in TouristRestService

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#86]
https://github.com/a3dot14makh/sf-senla-courses/blob/8c68bbbd6ffaa6b0e289907660c6105100c4190c/lecture_2.7/TouristRestServiceTest.cls#L3

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/f8f3397e695b044f6e982e7c7eb44a4c9036ba60/lecture_2.7/TouristRestService.cls#L3
