### ISSUE TITLE
2.7.2 no asserts in Mock

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#87]
https://github.com/a3dot14makh/sf-senla-courses/blob/8c68bbbd6ffaa6b0e289907660c6105100c4190c/lecture_2.7/MockHttpResponseGenerator.cls#L6

**Comment by a3dot14makh** [comment]
Rebuilded the logic.

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/4a620fad8bda77c761a2f0498628d0df8e15cc46/lecture_2.7/ErrorMockResponse.cls#L1
