### ISSUE TITLE
2.7.2 grammar mistakes are not allowed

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#88]
https://github.com/a3dot14makh/sf-senla-courses/blob/8c68bbbd6ffaa6b0e289907660c6105100c4190c/lecture_2.7/MockHttpResponseGenerator.cls#L17

**Comment by NikitaErmakSenla** [comment]
Still relevant

**Comment by a3dot14makh** [comment]
Ok
