### ISSUE TITLE
2.7.2 Not transparent logic. Create several Mocks for different test cases

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#89]
https://github.com/a3dot14makh/sf-senla-courses/blob/8c68bbbd6ffaa6b0e289907660c6105100c4190c/lecture_2.7/MockHttpResponseGenerator.cls#L11

**Comment by NikitaErmakSenla** [comment]
Should not be combined this way

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/f8f3397e695b044f6e982e7c7eb44a4c9036ba60/lecture_2.7/WeatherForecastServiceTest.cls#L13

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/commit/c5904ac92569d1b4f6314208a636e610058ab02d
