### ISSUE TITLE
2.4 rename ExceptionHw.cls -> ExceptionsPlayground.cls

### ISSUE THREAD

**Issue by alexCherrySfds2019** [a3dot14makh/sf-senla-courses#9]
https://github.com/a3dot14makh/sf-senla-courses/blob/3a8db34086827c9a429d6d7b7a58257891c38207/lecture_2.4/ExceptionHw.cls#L1

давай дадим более осмысленные названия:
ExceptionHw.cls -> ExceptionsPlayground.cls
testExceptionOne -> generateCustomException
testExceptionTwo -> generateRegularException
testExceptionThree -> handleExceptions

**Comment by a3dot14makh** [comment]
Done
