### ISSUE TITLE
2.7.2 if error not happens then unit-test will be also finished successfully 

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#90]
https://github.com/a3dot14makh/sf-senla-courses/blob/8c68bbbd6ffaa6b0e289907660c6105100c4190c/lecture_2.7/WeatherForecastServiceTest.cls#L42

**Comment by NikitaErmakSenla** [comment]
Still relevant

**Comment by a3dot14makh** [comment]
I've learned.
https://github.com/a3dot14makh/sf-senla-courses/blob/4a620fad8bda77c761a2f0498628d0df8e15cc46/lecture_2.7/WeatherForecastServiceTest.cls#L43

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/4a620fad8bda77c761a2f0498628d0df8e15cc46/lecture_2.7/ErrorMockResponse.cls#L1
