### ISSUE TITLE
3.4 Move logic to FlightService

### ISSUE THREAD

**Issue by NikitaErmakSenla** [a3dot14makh/sf-senla-courses#96]
https://github.com/a3dot14makh/sf-senla-courses/blob/113c340332974f118cd1f00759a136168b1ea1d0/lecture_3.4/classes/TableSuitableTouristsForTripController.cls#L29

**Comment by a3dot14makh** [comment]
https://github.com/a3dot14makh/sf-senla-courses/blob/4f4b49fd3f711f4973ac699bfb87abab474f2f3b/lecture_3.4/classes/TripService.cls#L3

**Comment by alexCherrySfds2019** [comment]
@NikitaErmakSenla could be closed
